// Turns the uploaded project files into web images.
//
//   assets/projects/<folder>/face.*     ->  assets/web/<slug>/cover.webp
//   assets/projects/<folder>/slide*.*   ->  assets/web/<slug>/slide-01.webp, -02…
//
// Slides are long scroll-through boards (up to 32k px tall), so each is
// scaled to SLIDE_W and cut into CHUNK_H-tall pieces that stack seamlessly on
// the project page and load progressively. Writes js/assets.generated.js,
// which the site reads — rerun after uploading new files:
//
//   node tools/build-slides.mjs
import sharp from "sharp";
import { readdir, mkdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

// upload folder -> project slug in js/projects.js
const SOURCES = {
  "rebrush": "rebrush",
  "cmf": "creta-cmf",
  "detailing and assembly": "lapcare",
  "interactive product design": "anchor",
  "latent": "latent",
};

// Projects whose face image isn't ready yet: crop the cover from the top of
// the slide instead. Remove a slug from here once its real face is uploaded.
const COVER_FROM_SLIDE = new Set(["creta-cmf"]);

const ROOT = new URL("..", import.meta.url).pathname;
const IN = join(ROOT, "assets/projects");
const OUT = join(ROOT, "assets/web");
const COVER_W = 2000, SLIDE_W = 1600, CHUNK_H = 2000;
const IMG = /\.(jpe?g|png|webp|tiff?|avif)$/i;
const byName = (a, b) => a.localeCompare(b, undefined, { numeric: true });
const open = (f) => sharp(f, { limitInputPixels: false });

const assets = {};
for (const [folder, slug] of Object.entries(SOURCES)) {
  let files;
  try { files = (await readdir(join(IN, folder))).filter((f) => IMG.test(f)).sort(byName); }
  catch { console.warn(`! missing folder assets/projects/${folder}`); continue; }
  const dest = join(OUT, slug);
  await rm(dest, { recursive: true, force: true });
  await mkdir(dest, { recursive: true });
  const entry = (assets[slug] = { cover: "", slides: [] });

  const face = files.find((f) => /^(face|cover)\./i.test(f));
  const firstSlide = files.find((f) => /^slide/i.test(f));
  if (COVER_FROM_SLIDE.has(slug) && firstSlide) {
    const img = open(join(IN, folder, firstSlide));
    const { width } = await img.metadata();
    await img.extract({ left: 0, top: 0, width, height: Math.round(width * 9 / 16) })
      .resize({ width: COVER_W, withoutEnlargement: true }).webp({ quality: 82 }).toFile(join(dest, "cover.webp"));
    entry.cover = `assets/web/${slug}/cover.webp`;
  } else if (face) {
    await open(join(IN, folder, face)).rotate().resize({ width: COVER_W, withoutEnlargement: true }).webp({ quality: 82 }).toFile(join(dest, "cover.webp"));
    entry.cover = `assets/web/${slug}/cover.webp`;
  }

  let n = 0;
  for (const f of files.filter((f) => /^slide/i.test(f))) {
    const buf = await open(join(IN, folder, f)).rotate().resize({ width: SLIDE_W, withoutEnlargement: true }).png().toBuffer();
    const { width, height } = await sharp(buf, { limitInputPixels: false }).metadata();
    for (let top = 0; top < height; top += CHUNK_H) {
      const h = Math.min(CHUNK_H, height - top);
      const name = `slide-${String(++n).padStart(2, "0")}.webp`;
      await sharp(buf, { limitInputPixels: false }).extract({ left: 0, top, width, height: h }).webp({ quality: 80 }).toFile(join(dest, name));
      entry.slides.push({ src: `assets/web/${slug}/${name}`, w: width, h });
    }
  }
  console.log(`${folder} -> ${slug}: cover ${entry.cover ? "yes" : "no"}, ${entry.slides.length} slide pieces`);
}

await writeFile(join(ROOT, "js/assets.generated.js"),
  `// Generated by tools/build-slides.mjs — do not edit by hand.\nwindow.ASSETS = ${JSON.stringify(assets, null, 2)};\n`);
